version: '3'

services:

  ras-rabbit-adaptor-service:
    container_name: rabbit-adaptor
    image: sdcplatform/ras-rabbit-adaptor-service
    ports:
      - "8080:8080"
    environment:
      - CI_SECRETS=${CI_SECRETS}
      - COLLEX_ID=${COLLEX_ID}
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - BASIC_AUTH=(SECURITY_USER_NAME, SECURITY_USER_PASSWORD)
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
    networks:
      - rasrmdockerdev_default
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  sdx-seft-publisher-service:
    container_name: seft-publisher
    image: sdcplatform/sdx-seft-publisher-service
    ports:
      - "8086:8086"
    environment:
      - SEFT_FTP_USER=${SEFT_FTP_USER}
      - SEFT_FTP_PASS=${SEFT_FTP_PASS}
      - SEFT_FTP_HOST=${SEFT_FTP_HOST}
      - SEFT_FTP_PORT=${SEFT_FTP_PORT}
      - SEFT_RABBITMQ_HOST=${SEFT_RABBITMQ_HOST}
      - SEFT_RABBITMQ_PORT=${SEFT_RABBITMQ_PORT}
      - SEFT_RABBITMQ_DEFAULT_USER=guest
      - SEFT_RABBITMQ_DEFAULT_PASS=guest

    networks:
      - rasrmdockerdev_default
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.6.10-management
    ports:
      - "5369:4369"
      - "45672:25672"
      - "${EX_RABBIT_PORT}:5671-5672"
      - "16671-16672:15671-15672"
    networks:
      - rasrmdockerdev_default

  sftp:
    container_name: sftp
    image: atmoz/sftp
    volumes:
        - ~/Documents/sftp:/home/centos/Documents/sftp
    ports:
        - "${EX_SFTP_PORT}:22"
    command: centos:JLibV2&XD,:1001
    networks:
      - rasrmdockerdev_default

networks:
   rasrmdockerdev_default:
     external: true
