version: '3'

services:

  ras-rabbit-adaptor-service:
    container_name: rabbit-adaptor
    image: ras-rabbit-adaptor-service
    ports:
      - "8080:8080"
    environment:
      - CI_SECRETS=${CI_SECRETS}
      - COLLEX_ID=${COLLEX_ID}
      - SECURITY_USER_NAME=${SECURITY_USER_NAME}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD}
      - BASIC_AUTH=(SECURITY_USER_NAME, SECURITY_USER_PASSWORD)
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
    networks:
      - rasrmdockerdev_default
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  sdx-seft-publisher-service:
    container_name: seft-publisher
    image: sdx-seft-publisher-service
    ports:
      - "8086:8086"
    environment:
      - SEFT_FTP_USER=user
      - SEFT_FTP_PASS=pass
      - SEFT_FTP_HOST=sftp
      - SEFT_FTP_PORT=22
      - SEFT_RABBITMQ_HOST=${SEFT_RABBITMQ_HOST}
      - SEFT_RABBITMQ_PORT=${SEFT_RABBITMQ_PORT}
      - SEFT_RABBITMQ_DEFAULT_USER=guest
      - SEFT_RABBITMQ_DEFAULT_PASS=guest
      - SEFT_PUBLISHER_FTP_FOLDER=${SEFT_PUBLISHER_FTP_FOLDER}
      - SDX_SEFT_PUBLISHER_PORT=8086
      - SEFT_FTP_INTERVAL_MS=1800000
      - RAS_SEFT_PUBLISHER_PUBLIC_KEY=${RAS_SEFT_PUBLISHER_PUBLIC_KEY}
      - SDX_SEFT_PUBLISHER_PRIVATE_KEY=${SDX_SEFT_PUBLISHER_PRIVATE_KEY}
      - SEFT_RABBITMQ_MONITORING_USER=monitor
      - SEFT_RABBITMQ_MONITORING_PASS=monitor

    networks:
      - rasrmdockerdev_default
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/info"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.6.10-management
    ports:
      - "5369:4369"
      - "45672:25672"
      - "${EX_RABBIT_PORT}:5671-5672"
      - "16671-16672:15671-15672"
    networks:
      - rasrmdockerdev_default

  sftp:
    container_name: sftp
    image: atmoz/sftp
    volumes:
        - ~/Documents/ftp:/home/user/Documents/ftp
    ports:
        - "2222:22"
    command: user:pass:1001
    networks:
      - rasrmdockerdev_default
networks:
   rasrmdockerdev_default:
     external: true